# test envrionment configuration file
# ========================= server ==========================
# org.springframework.boot.autoconfigure.web.ServerProperties
server.port: 8080

# ========================= custome server ==================
# custome server config
servers:
  mina:
    enabled: true
    autostart: true
    filterLogConfig:
  #   exception handle by IoHandler
      exceptionCaughtLogLevel: none
      sessionCreatedLogLevel: debug
      sessionOpenedLogLevel: trace
      sessionClosedLogLevel: debug
      sessionIdleLogLevel: trace
    defaultPort: 10000
  #  bindAddresses: localhost:11111

# ========================= management =======================
# EndpointWebMvcManagementContextConfiguration
management:
  # EndpointWebMvcManagementContextConfiguration.endpointHandlerMapping()
  security.enabled: false
  # port: 11111
  port: ${server.port}
  # actuator url prefix see: EndpointWebMvcManagementContextConfiguration.endpointHandlerMapping()
  contextPath: /management

# ======================== spring ===============================
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
  jackson:
    defaultPropertyInclusion: NON_NULL
    serialization:
      indent_output: true
      fail_on_empty_beans: false
    parser:
      allow_missing_values: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
# jpa.hibernate.ddl-auto: validate
  h2.console:
    enabled: true
    path: /h2-console
  devtools:
    restart.enabled: false
  datasource:
    mysql:
      url: jdbc:mysql://192.168.56.101:3306/test
      username: root
      password: mysql
    h2:
      schema:
      data: 
      url: jdbc:h2:./data/h2/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: test
      password: test
      max-active: 3

# ========================= logging ==============================
#logging.path和logging.file同时配置，不会有在这个路径有F:\demo\demo.log日志生成，logging.path和logging.file不会进行叠加
#logging.path和logging.file的value都可以是相对路径或者绝对路径
logging:
  file: D:\tmp\log\spring-boot.log
#  pattern:
#    console:
#    file:
#    level:
  level:
    root: info
    my.server.mina.autoconfigure.MinaAcceptorAutoConfigure: trace
    my.server.mina.codec.DeviceCollectDataRequestDecoder: trace
    my.server.mina.handler.RequestDataProcessor: trace
    my.server.mina.handler.ResponseProcessor: trace
    my.server.mina.handler.ValidateProcessor: trace
    my.server.mina.handler.DeviceCollectDataIoHandler: trace
    org.apache.mina.filter.logging.LoggingFilter: trace
    my.util.handler.HandlerChain: trace
    my.controller.TestRestController: trace
    # controller method invoke detail
#    org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod: trace