# test envrionment configuration file
spring:
  jackson:
    defaultPropertyInclusion: NON_NULL
    serialization:
      indent_output: true
      fail_on_empty_beans: false
    parser:
      allow_missing_values: true
#  jpa.hibernate.ddl-auto: validate
  h2.console:
    enabled: true
    path: /h2-console
  devtools:
    restart.enabled: false
  datasource:
    mysql:
      url: jdbc:mysql://192.168.56.101:3306/test
      username: root
      password: mysql
    h2:
      schema:
      data: 
      url: jdbc:h2:./data/h2/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: test
      password: test
      max-active: 3

logging:
  file: D:\tmp\spring-boot.log
  level:
    my.autoconfigure.IoAcceptorAutoConfigure: trace
    my.ioServer.codec.DeviceCollectDataRequestDecoder: trace
    org.apache.mina.filter.logging.LoggingFilter: trace
    my.ioServer.handler.DeviceCollectDataIoHandler: trace
    my.util.handler.HandlerChain: trace
    my.ioServer.handler.RequestDataProcessor: trace
    my.ioServer.handler.ResponseProcessor: trace
    my.ioServer.handler.ValidateProcessor: trace
    my.controller.TestRestController: trace
    # controller method invoke detail
    org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod: trace

# io server config
ioServer:
  filterLogConfig:
#   exception handle by IoHandler
    exceptionCaughtLogLevel: none
    sessionCreatedLogLevel: debug
    sessionOpenedLogLevel: trace
    sessionClosedLogLevel: debug
    sessionIdleLogLevel: trace
  defaultPort: 10000
#  bindAddresses: localhost:11111